-- CreateEnum
CREATE TYPE "WikiType" AS ENUM ('GENERAL', 'STORY', 'AREA', 'CHARACTER', 'OBJECT', 'HISTORY', 'SCIENCE', 'EXPLANATION', 'OTHER');

-- AlterTable
ALTER TABLE "Wiki" ADD COLUMN     "featured" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "type" "WikiType" NOT NULL DEFAULT 'GENERAL';
