-- AlterTable
ALTER TABLE "Map" ADD COLUMN     "canvasAspectRatio" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "mapHeight" INTEGER NOT NULL DEFAULT 1000,
ADD COLUMN     "mapWidth" INTEGER NOT NULL DEFAULT 1000;
